package com.ihu.scorm.engine.common.error;

public enum ErrorCode {
  ACTIVE_ATTEMPT_EXISTS("ACTIVE_ATTEMPT_EXISTS"),
  ATTEMPT_NOT_FOUND("ATTEMPT_NOT_FOUND"),
  BAD_REQUEST("BAD_REQUEST"),
  COURSE_NOT_FOUND("COURSE_NOT_FOUND"),
  EMAIL_EXISTS("EMAIL_EXISTS"),
  ENROLLMENT_EXISTS("ENROLLMENT_EXISTS"),
  ENROLLMENT_NOT_FOUND("ENROLLMENT_NOT_FOUND"),
  ENTRYPOINT_NOT_FOUND("ENTRYPOINT_NOT_FOUND"),
  FORBIDDEN("FORBIDDEN"),
  INTERNAL_ERROR("INTERNAL_ERROR"),
  INVALID_FILE("INVALID_FILE"),
  INVALID_LAUNCH_TOKEN("INVALID_LAUNCH_TOKEN"),
  INVALID_ZIP("INVALID_ZIP"),
  LAUNCH_CLOSED("LAUNCH_CLOSED"),
  LAUNCH_EXPIRED("LAUNCH_EXPIRED"),
  LAUNCH_NOT_FOUND("LAUNCH_NOT_FOUND"),
  MANIFEST_INVALID("MANIFEST_INVALID"),
  MANIFEST_NOT_FOUND("MANIFEST_NOT_FOUND"),
  MANIFEST_PARSE_ERROR("MANIFEST_PARSE_ERROR"),
  RUNTIME_RATE_LIMIT("RUNTIME_RATE_LIMIT"),
  SEQUENCE_OUTDATED("SEQUENCE_OUTDATED"),
  TOKEN_LAUNCH_MISMATCH("TOKEN_LAUNCH_MISMATCH"),
  TOKEN_MISMATCH("TOKEN_MISMATCH"),
  UNAUTHENTICATED("UNAUTHENTICATED"),
  UNSUPPORTED_MEDIA_TYPE("UNSUPPORTED_MEDIA_TYPE"),
  UNSUPPORTED_STANDARD("UNSUPPORTED_STANDARD"),
  USERNAME_EXISTS("USERNAME_EXISTS"),
  USER_NOT_FOUND("USER_NOT_FOUND"),
  VALIDATION_ERROR("VALIDATION_ERROR");

  private final String value;

  ErrorCode(String value) {
    this.value = value;
  }

  public String value() {
    return value;
  }
}
